### ISSUE TITLE
Would it works for N82 & N95?

### ISSUE THREAD

**Issue by Symbian9** [NuruTasDemir/symbian-mods-new#1]
It fix SHA2 issue for Nokia N82 & N95 smartphones?

**Comment by Symbian9** [comment]
Cast @fedor4ever, @pent0, @nikita36078

**Comment by fedor4ever** [comment]
I don't know. Anyway all sites will use tls 1.3 which unsupported by symbian.

**Comment by NuruTasDemir** [comment]
Sorry for answering late, it works all Symbian 9.1, 9.2, 9.3 and 9.4 devices
